### ISSUE TITLE
Nutzerführung 

### ISSUE THREAD

**Issue by Clickmari** [University-of-Potsdam-MM/UPReflection#23]
"Die Benutzer wissen nicht wofür die Fragen unten da sind. Daher müsste irgendwo bei Fragen sowas wie ein Fragezeichen mit erläuternden Text"

-> Menu mit  -Reflektionsfragen, -mehr Termine, -Feedabck sollte die Buttons, die irgendwo zwischendrin oder oben drüber auftauchen verschwinden machen.

**Comment by Clickmari** [comment]
Reflektionsfragen, Feedback und Termine müssen eine eigene Seite bekommen

**Comment by alekiy** [comment]
- vllt. ein Side-Panel für die übergreifenden Punkte benutzen?
- wie sieht es mit der Zurück-Verlinkung in den Hauptseiten (Feedback, Termine, Fragen, Impressum aus?)

**Comment by alekiy** [comment]
Panel und Infopanel für Reflexionsfragen hinzugefügt see 930dc4f6a2c19e15e423bdc53363409086c55192
