### ISSUE TITLE
Fragen vorausgewählt

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/UPReflection#26]
- [x] Bei den Fragen sind sind die Antworten vorausgewählt, was schon eine "richtige" Antwort suggeriert.
- [x] Es wäre auch noch einfacher zu bedienen, wenn auch mit Klick auf die Schrift eine Auswahl der Antwort stattfinden könnte.
- [x] Bei den Terminen stehen einige doppelt drin.

**Comment by ItsNotYou** [comment]
O-Ton Alex: "Die standen im Moodle-Kurs doppelt drin, deswegen wurden sie auch doppelt angezeigt."
