### ISSUE TITLE
Bullet Points vergrößern

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/UPReflection#28]
Die Bullet Points vergrößern, damit die Auswahl leichter fällt.

**Comment by ItsNotYou** [comment]
Mir werden keine Bullet Points angezeigt, dafür aber zwei fehlende Bilder:

http://localhost/reflectup/elements/extruder_blank.png
http://localhost/reflectup/elements/extruder_voiceHover.png

**Comment by alekiy** [comment]
Dateien siehe: https://github.com/pupunzi/jquery.mb.extruder
