### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/UPReflection#30]
Zeitmanagement 1/2: zurecht "Application Error" nach
Beantwortung Zeitmanagement

**Comment by ItsNotYou** [comment]
Das Problem kann ich nicht reproduzieren.

**Comment by ItsNotYou** [comment]
Alex sagt: "Schließen!"

**Comment by Clickmari** [comment]
Wo is eigentlich der Katzenhintergrund?
