### ISSUE TITLE
Kontaktdaten für wichtige Ansprechpartner hinzufügen

### ISSUE THREAD

**Issue by alekiy** [University-of-Potsdam-MM/UPReflection#36]

**Comment by alekiy** [comment]
Bitte einen Reiter für Ansprechpartner im Seitenpanel hinufügen. Die Ansprechpartner stehen im Moodle-Kurs.

**Comment by ItsNotYou** [comment]
- [ ] Der Ansprechpartner-Button im Sidepanel benötigt ein Icon

Die anderen Punkte gelten für die Ansprechpartner-Seite
- [ ] Telefonnummern sind klickbar und sollten entsprechend hervorgehoben werden
- [ ] Mail-Adressen sind klickbar und sollten entsprechend hervorgehoben werden
- [ ] Konsultations-URLs (siehe Maja Apelt) sind klickbar und sollten entsprechend hervorgehoben werden

**Comment by ItsNotYou** [comment]
Die externen Links sind mit der Klasse "external" markiert.

**Comment by alekiy** [comment]
see http://fortawesome.github.io/Font-Awesome/icon/users/
